### PR TITLE
WAS-435 - review page (check details)

### PR DESCRIPTION
**Pull request by autotelik**
**This PR**

Implements WAS-435 - Complete the full stack for Check details page a.k.a Review

New DSL to seperate processing from content - locale content can drive dynamic page construction
Associated page object for view/feature testing
Feature test checking page structure, content, links back.
Specs to support above.

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Thanks for getting it passing @autotelik. Could you walk me through how it works tomorrow?

**Comment by Cruikshanks** [comment]
Just so you know, we're working on the basis that you'll re-assign the PR to me when its ready to be looked over and merged in. Don't think anyone ever told you that in case you're sat there waiting for me to do something :see_no_evil:.

**Comment by autotelik** [comment]
@Cruikshanks yeah thanks, this story is still with content designers/UX so the PR is open (for foreseeable future)

**Comment by Cruikshanks** [comment]
Admittedly quickly reviewed by the devs. Agreed that we would add **deprecated** to the file names which contain the old way of generating the review, and move the **stackprof** gem to the dev & test group, but these can be done separately :imp:

**Pull request merged**
