### PR TITLE
Add Version Page

### PR DESCRIPTION
**Pull request by rickclare**
This PR adds a "version page" to allow users (e.g. Devs or QAs) to
determine which version (and git commit) is being run on each Rails
server

### CODE REVIEW

**Comment by rickclare** [comment]
@Cruikshanks Over to you to PR and to create a temporary Heroku app to test this on.

**Comment by rickclare** [comment]
The page will be accessible at:

https://<app>.herokuapp.com/pages/version

**Comment by Cruikshanks** [comment]
Have got it running in a heroku app ([waste-exemptions-dv](https://waste-exemptions-dv.herokuapp.com/pages/version) however its not displaying and giving an error page instead. Just need to figure out what the problem is first.

**Comment by rickclare** [comment]
@Cruikshanks  This is now corrected. 

https://waste-exemptions-dv.herokuapp.com/pages/version

Note: When we merge to develop, we will need to execute the following:


```
heroku buildpacks:clear --app waste-exemptions
heroku buildpacks:clear --app waste-exemptions-qa
heroku buildpacks:clear --app waste-exemptions-ut
heroku buildpacks:clear --app waste-exemptions-dv

heroku buildpacks:set https://github.com/heroku/heroku-buildpack-multi.git --app waste-exemptions
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-multi.git --app waste-exemptions-qa
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-multi.git --app waste-exemptions-ut
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-multi.git --app waste-exemptions-dv


```

**Pull request merged**
