### PR TITLE
WAS-517: Correspondence contact page

### PR DESCRIPTION
**Pull request by rickclare**

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Repeated attempts in [travis-ci](https://travis-ci.org/EnvironmentAgency/waste-exemptions/builds/85318913) illicit the same result; its failing with the error

```
/home/travis/build/EnvironmentAgency/waste-exemptions/spec/support/page_objects/organisation_type/individual_organisation_address_po.rb:2:in `<module:OrganisationType>': uninitialized constant BaseOrganisationAddressPage (NameError)
```

Any ideas? I would want travis passing before I could merge.

**Comment by rickclare** [comment]
@Cruikshanks That's are really weird one. `BaseOrganisationAddressPage` was introduced in WAS-373 (Business Address Page) - i.e. it isn't a new class and isn't related to this PR.  I will investigate further.

**Comment by rickclare** [comment]
@Cruikshanks specs are not passing on this branch, after cherry-picking Tom's factory changes.

**Comment by Cruikshanks** [comment]
Happy for this to be merged @rickclare I'll leave it with you to handle the conflicts.

**Pull request merged**
